### ISSUE TITLE
Doesn't turn all processors back on

### ISSUE THREAD

**Issue by FoxoManiak** [jackdaniels552/r6lagfix#1]
I noticed my game would get instable fps after turning it on, thought its just my processor not handling it somehow

I tried doing it manually once and noticed that after the code did its thing, it turned only 3 processors back on, instead of 4 I have, that was the cause of fps instability i was experiencing 

The code did see me having 4 so not sure whats going wrong with it.

**Comment by jackdaniels552** [comment]
This fix only sometimes works. Sadly its a hit and miss. Mostly did this so people wouldn't have to do it manually. Not using 1 core on that process wouldn't give unstable fps unless your on a dual core or something like that. Sadly this has stopped working for me as well as a fix.

**Comment by jackdaniels552** [comment]
This should be patched in the 1.6 Pre-Release https://github.com/jackdaniels552/r6lagfix/releases
